create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  provider text not null default 'email' check (provider in ('email', 'Kakao', 'Google', 'Naver')),
  provider_subject text,
  display_name text not null,
  phone text not null default '',
  postal_code text not null default '',
  address_line1 text not null default '',
  address_line2 text not null default '',
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_unique on public.profiles (lower(email)) where email is not null;

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  summary text not null default '',
  description text not null default '',
  price integer not null check (price >= 0),
  compare_at_price integer not null default 0 check (compare_at_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  status text not null check (status in ('active', 'draft', 'soldout')),
  featured boolean not null default false,
  art text not null default 'box',
  palette_json jsonb not null default '["#f3eee6", "#ddd0bf"]'::jsonb,
  accent text not null default '#7a5e45',
  image_url text,
  options_json jsonb not null default '[]'::jsonb,
  details_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id text primary key,
  title text not null,
  category text not null check (category in ('notice', 'journal', 'event')),
  excerpt text not null default '',
  content text not null default '',
  status text not null check (status in ('draft', 'published')),
  pinned boolean not null default false,
  cover_image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  product_id text not null references public.products(id) on delete restrict,
  product_name text not null,
  option_name text not null,
  quantity integer not null check (quantity between 1 and 99),
  total integer not null check (total >= 0),
  customer_name text not null,
  phone text not null,
  address text not null,
  payment_method text not null check (payment_method in ('card', 'kakao', 'naver')),
  delivery_note text not null default '',
  status text not null check (status in ('paid', 'preparing', 'shipping', 'delivered', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id text primary key,
  product_id text not null references public.products(id) on delete cascade,
  product_name text not null,
  author text not null,
  rating integer not null check (rating between 1 and 5),
  option_name text not null default '',
  body text not null,
  status text not null check (status in ('visible', 'hidden')),
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id smallint primary key check (id = 1),
  store_name text not null,
  announcement text not null default '',
  shipping_notice text not null default '',
  support_email text not null default '',
  support_phone text not null default '',
  footer_description text not null default '',
  maintenance_mode boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.imported_products (
  id text primary key,
  owner_id uuid references auth.users(id) on delete set null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  option_name text not null,
  quantity integer not null check (quantity between 1 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id, option_name)
);

create table if not exists public.wishlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.restock_requests (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.purchase_requests (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  imported_product_id text not null references public.imported_products(id) on delete cascade,
  product_name text not null,
  option_name text not null default '',
  request_note text not null default '',
  estimated_total integer not null default 0 check (estimated_total >= 0),
  status text not null default 'requested' check (status in ('requested', 'reviewing', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists products_status_created_idx on public.products (status, created_at desc);
create index if not exists posts_status_updated_idx on public.posts (status, updated_at desc);
create index if not exists orders_user_created_idx on public.orders (user_id, created_at desc);
create index if not exists reviews_product_status_idx on public.reviews (product_id, status, created_at desc);
create index if not exists cart_items_user_idx on public.cart_items (user_id);
create index if not exists purchase_requests_user_idx on public.purchase_requests (user_id, created_at desc);

create or replace function private.normalize_provider(value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case lower(coalesce(value, 'email'))
    when 'kakao' then 'Kakao'
    when 'google' then 'Google'
    when 'naver' then 'Naver'
    else 'email'
  end
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  provider_name text;
begin
  provider_name := private.normalize_provider(coalesce(new.raw_app_meta_data ->> 'provider', new.raw_user_meta_data ->> 'provider'));
  insert into public.profiles (
    id, email, provider, provider_subject, display_name, phone, postal_code,
    address_line1, address_line2, created_at, updated_at
  ) values (
    new.id,
    new.email,
    provider_name,
    new.raw_app_meta_data ->> 'provider_id',
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), nullif(new.raw_user_meta_data ->> 'full_name', ''), nullif(new.raw_user_meta_data ->> 'name', ''), split_part(coalesce(new.email, 'TO YOU 회원'), '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'postal_code', ''),
    coalesce(new.raw_user_meta_data ->> 'address_line1', ''),
    coalesce(new.raw_user_meta_data ->> 'address_line2', ''),
    now(),
    now()
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure private.handle_new_user();

create or replace function private.is_admin(requesting_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select p.is_admin from public.profiles p where p.id = requesting_user), false)
$$;

create or replace function private.update_my_profile(requesting_user uuid, profile_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_profile public.profiles%rowtype;
  requested_email text := lower(trim(coalesce(profile_data ->> 'email', '')));
  requested_name text := trim(coalesce(profile_data ->> 'name', ''));
  email_changed boolean := false;
begin
  if requesting_user is null then raise exception '로그인이 필요합니다.'; end if;
  select * into current_profile from public.profiles where id = requesting_user for update;
  if not found then raise exception '회원정보를 찾을 수 없습니다.'; end if;

  if current_profile.provider <> 'email' then
    if requested_name <> current_profile.display_name or requested_email <> coalesce(current_profile.email, '') then
      raise exception '간편가입 계정의 이름과 이메일은 가입한 서비스에서 변경해 주세요.';
    end if;
  else
    if length(requested_name) < 2 then raise exception '이름을 2자 이상 입력해 주세요.'; end if;
    if requested_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception '올바른 이메일 주소를 입력해 주세요.'; end if;
    email_changed := requested_email <> coalesce(current_profile.email, '');
  end if;

  update public.profiles set
    email = case when provider = 'email' then requested_email else email end,
    display_name = case when provider = 'email' then requested_name else display_name end,
    phone = left(trim(coalesce(profile_data ->> 'phone', '')), 40),
    postal_code = left(trim(coalesce(profile_data ->> 'postalCode', '')), 20),
    address_line1 = left(trim(coalesce(profile_data ->> 'addressLine1', '')), 300),
    address_line2 = left(trim(coalesce(profile_data ->> 'addressLine2', '')), 300),
    updated_at = now()
  where id = requesting_user;

  return jsonb_build_object('email_changed', email_changed);
end;
$$;

create or replace function public.update_my_profile(p_profile jsonb)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.update_my_profile((select auth.uid()), p_profile) $$;

create or replace function private.create_store_order(requesting_user uuid, order_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_product public.products%rowtype;
  saved_order public.orders%rowtype;
  updated_product public.products%rowtype;
  requested_quantity integer;
  selected_option text;
  subtotal integer;
begin
  if requesting_user is null then raise exception '로그인이 필요합니다.'; end if;
  requested_quantity := greatest(1, least(99, coalesce((order_data ->> 'quantity')::integer, 1)));
  selected_option := left(trim(coalesce(order_data ->> 'option', '')), 200);

  if length(trim(coalesce(order_data ->> 'customerName', ''))) < 2
    or length(regexp_replace(coalesce(order_data ->> 'phone', ''), '[^0-9]', '', 'g')) < 9
    or length(trim(coalesce(order_data ->> 'address', ''))) < 5 then
    raise exception '주문자와 배송지 정보를 확인해 주세요.';
  end if;

  select * into selected_product
  from public.products
  where id = order_data ->> 'productId' and status = 'active'
  for update;

  if not found then raise exception '판매 중인 상품을 찾을 수 없습니다.'; end if;
  if selected_product.stock < requested_quantity then raise exception '주문 가능한 재고가 부족합니다.'; end if;
  if jsonb_array_length(selected_product.options_json) > 0 and not (selected_product.options_json ? selected_option) then
    raise exception '상품 옵션을 다시 선택해 주세요.';
  end if;

  subtotal := selected_product.price * requested_quantity;
  insert into public.orders (
    id, user_id, product_id, product_name, option_name, quantity, total, customer_name,
    phone, address, payment_method, delivery_note, status, created_at
  ) values (
    'ord-' || gen_random_uuid()::text,
    requesting_user,
    selected_product.id,
    selected_product.name,
    selected_option,
    requested_quantity,
    subtotal + case when subtotal >= 70000 then 0 else 3000 end,
    left(trim(order_data ->> 'customerName'), 100),
    left(trim(order_data ->> 'phone'), 40),
    left(trim(order_data ->> 'address'), 1000),
    case when order_data ->> 'paymentMethod' in ('card', 'kakao', 'naver') then order_data ->> 'paymentMethod' else 'card' end,
    left(trim(coalesce(order_data ->> 'deliveryNote', '')), 1000),
    'paid',
    now()
  ) returning * into saved_order;

  update public.products
  set stock = stock - requested_quantity,
      status = case when stock - requested_quantity = 0 then 'soldout' else status end,
      updated_at = now()
  where id = selected_product.id
  returning * into updated_product;

  return jsonb_build_object('order', to_jsonb(saved_order), 'product', to_jsonb(updated_product));
end;
$$;

create or replace function public.create_store_order(p_order jsonb)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.create_store_order((select auth.uid()), p_order) $$;

revoke execute on function public.create_store_order(jsonb) from anon;
grant execute on function public.create_store_order(jsonb) to authenticated;

create or replace function private.update_store_order_status(requesting_user uuid, requested_order_id text, requested_status text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_order public.orders%rowtype;
  selected_product public.products%rowtype;
begin
  if not private.is_admin(requesting_user) then raise exception '관리자 권한이 없습니다.'; end if;
  if requested_status not in ('paid', 'preparing', 'shipping', 'delivered', 'cancelled') then raise exception '올바른 주문 상태가 아닙니다.'; end if;

  select * into selected_order from public.orders where id = requested_order_id for update;
  if not found then raise exception '주문을 찾을 수 없습니다.'; end if;
  select * into selected_product from public.products where id = selected_order.product_id for update;

  if selected_order.status <> 'cancelled' and requested_status = 'cancelled' then
    update public.products set stock = stock + selected_order.quantity,
      status = case when status = 'soldout' then 'active' else status end, updated_at = now()
    where id = selected_order.product_id returning * into selected_product;
  elsif selected_order.status = 'cancelled' and requested_status <> 'cancelled' then
    if selected_product.stock < selected_order.quantity then raise exception '주문을 복구할 재고가 부족합니다.'; end if;
    update public.products set stock = stock - selected_order.quantity,
      status = case when stock - selected_order.quantity = 0 then 'soldout' else status end, updated_at = now()
    where id = selected_order.product_id returning * into selected_product;
  end if;

  update public.orders set status = requested_status where id = selected_order.id returning * into selected_order;
  return jsonb_build_object('order', to_jsonb(selected_order), 'product', to_jsonb(selected_product));
end;
$$;

create or replace function public.update_store_order_status(p_order_id text, p_status text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.update_store_order_status((select auth.uid()), p_order_id, p_status) $$;

create or replace function private.add_cart_items(requesting_user uuid, items jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  selected_product public.products%rowtype;
  requested_quantity integer;
  selected_option text;
begin
  if requesting_user is null then raise exception '로그인이 필요합니다.'; end if;
  for item in select value from jsonb_array_elements(items)
  loop
    requested_quantity := greatest(1, least(99, coalesce((item ->> 'quantity')::integer, 1)));
    selected_option := left(trim(coalesce(item ->> 'option', '')), 200);
    select * into selected_product from public.products where id = item ->> 'productId' and status = 'active';
    if not found then raise exception '장바구니에 담을 상품을 찾을 수 없습니다.'; end if;
    if jsonb_array_length(selected_product.options_json) > 0 and not (selected_product.options_json ? selected_option) then
      raise exception '상품 옵션을 다시 선택해 주세요.';
    end if;
    if selected_product.stock < 1 then raise exception '주문 가능한 재고가 없습니다.'; end if;

    insert into public.cart_items (user_id, product_id, option_name, quantity, created_at, updated_at)
    values (requesting_user, selected_product.id, selected_option, least(requested_quantity, selected_product.stock), now(), now())
    on conflict (user_id, product_id, option_name) do update
      set quantity = least(public.cart_items.quantity + excluded.quantity, selected_product.stock), updated_at = now();
  end loop;
end;
$$;

create or replace function public.add_cart_items(p_items jsonb)
returns void
language sql
security invoker
set search_path = ''
as $$ select private.add_cart_items((select auth.uid()), p_items) $$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.posts enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;
alter table public.store_settings enable row level security;
alter table public.imported_products enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlists enable row level security;
alter table public.restock_requests enable row level security;
alter table public.purchase_requests enable row level security;

create policy "profiles_select_own_or_admin" on public.profiles for select to authenticated
  using ((select auth.uid()) = id or private.is_admin());
create policy "profiles_admin_all" on public.profiles for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "products_public_read" on public.products for select to anon, authenticated
  using (status in ('active', 'soldout') or private.is_admin());
create policy "products_admin_all" on public.products for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "posts_public_read" on public.posts for select to anon, authenticated
  using (status = 'published' or private.is_admin());
create policy "posts_admin_all" on public.posts for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "orders_select_own_or_admin" on public.orders for select to authenticated
  using ((select auth.uid()) = user_id or private.is_admin());
create policy "orders_admin_all" on public.orders for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "reviews_public_read" on public.reviews for select to anon, authenticated
  using (status = 'visible' or private.is_admin());
create policy "reviews_admin_all" on public.reviews for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "settings_public_read" on public.store_settings for select to anon, authenticated using (true);
create policy "settings_admin_all" on public.store_settings for all to authenticated
  using (private.is_admin()) with check (private.is_admin());

create policy "imported_products_public_read" on public.imported_products for select to anon, authenticated using (true);
create policy "imported_products_insert_own" on public.imported_products for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "imported_products_update_own_or_admin" on public.imported_products for update to authenticated
  using ((select auth.uid()) = owner_id or private.is_admin())
  with check ((select auth.uid()) = owner_id or private.is_admin());
create policy "imported_products_delete_own_or_admin" on public.imported_products for delete to authenticated
  using ((select auth.uid()) = owner_id or private.is_admin());

create policy "cart_items_own" on public.cart_items for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "wishlists_own" on public.wishlists for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "restock_requests_own" on public.restock_requests for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "purchase_requests_own_or_admin" on public.purchase_requests for select to authenticated
  using ((select auth.uid()) = user_id or private.is_admin());
create policy "purchase_requests_insert_own" on public.purchase_requests for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "purchase_requests_admin_update" on public.purchase_requests for update to authenticated
  using (private.is_admin()) with check (private.is_admin());

grant usage on schema public to anon, authenticated;
grant usage on schema private to anon, authenticated;
grant select on public.products, public.posts, public.reviews, public.store_settings, public.imported_products to anon;
grant select on all tables in schema public to authenticated;
grant insert, update, delete on public.products, public.posts, public.reviews, public.store_settings, public.imported_products,
  public.cart_items, public.wishlists, public.restock_requests, public.purchase_requests to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.update_my_profile(jsonb) from public;
revoke all on function public.create_store_order(jsonb) from public;
revoke all on function public.update_store_order_status(text, text) from public;
revoke all on function public.add_cart_items(jsonb) from public;
revoke all on function private.update_my_profile(uuid, jsonb) from public;
revoke all on function private.create_store_order(uuid, jsonb) from public;
revoke all on function private.update_store_order_status(uuid, text, text) from public;
revoke all on function private.add_cart_items(uuid, jsonb) from public;
revoke all on function private.is_admin(uuid) from public;

grant execute on function public.update_my_profile(jsonb) to authenticated;
grant execute on function public.create_store_order(jsonb) to authenticated;
grant execute on function public.update_store_order_status(text, text) to authenticated;
grant execute on function public.add_cart_items(jsonb) to authenticated;
grant execute on function private.update_my_profile(uuid, jsonb) to authenticated;
grant execute on function private.create_store_order(uuid, jsonb) to authenticated;
grant execute on function private.update_store_order_status(uuid, text, text) to authenticated;
grant execute on function private.add_cart_items(uuid, jsonb) to authenticated;
grant execute on function private.is_admin(uuid) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "product_images_public_read" on storage.objects for select to public
  using (bucket_id = 'product-images');
create policy "product_images_admin_insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'product-images' and private.is_admin());
create policy "product_images_admin_update" on storage.objects for update to authenticated
  using (bucket_id = 'product-images' and private.is_admin())
  with check (bucket_id = 'product-images' and private.is_admin());
create policy "product_images_admin_delete" on storage.objects for delete to authenticated
  using (bucket_id = 'product-images' and private.is_admin());

insert into public.store_settings (
  id, store_name, announcement, shipping_notice, support_email, support_phone, footer_description, maintenance_mode
) values (
  1, 'TO YOU', '신규 회원 첫 구매 10% 혜택 · 7만원 이상 무료배송', '평일 오후 2시 이전 주문은 당일 출고됩니다.',
  'hello@toyou-store.kr', '02-1234-5678', '매일 가까이 두고 싶은 물건을 소개합니다.', false
) on conflict (id) do nothing;

insert into public.products (
  id, name, category, summary, description, price, compare_at_price, stock, status, featured,
  art, palette_json, accent, options_json, details_json, created_at, updated_at
) values
  ('orb-case', 'Orb Ripple MagSafe Case', '테크', '투명 실버 프레임과 글로시 웨이브 패턴이 섞인 테크 액세서리', '빛에 따라 웨이브 패턴이 드러나는 MagSafe 하드 케이스입니다.', 32000, 39000, 24, 'active', false, 'case', '["#ffe8ef", "#f7bfd0"]', '#ad2347', '["iPhone 15 Pro / Silver", "iPhone 16 / Clear Pink", "Galaxy S25 / Mirror"]', '["MagSafe 자석 링 내장", "PC와 TPU 혼합 소재", "실버 엣지 유광 마감"]', '2026-07-12T00:00:00Z', now()),
  ('cloud-bag', 'Cloud Pocket Big Bag', '패션', '부드러운 나일론 볼륨감과 넉넉한 수납력이 매력적인 빅 백', '가벼운 나일론 원단과 안정적인 하단 패널을 적용한 데일리 숄더백입니다.', 74200, 89000, 11, 'active', true, 'bag', '["#ebf4ff", "#b4d0ff"]', '#2458c5', '["Sky Blue / Free", "Ivory / Free", "Graphite / Free"]', '["외부 포켓 2개", "13인치 노트북 수납", "가벼운 나일론 원단"]', '2026-07-11T00:00:00Z', now()),
  ('dew-drop', 'Dew Reset Glow Ampoule', '뷰티', '아침 피부 톤을 화사하게 끌어올리는 광채 앰플 세트', '수분감 위주의 가벼운 제형으로 메이크업 전 피부 표현을 정돈합니다.', 24800, 32000, 38, 'active', false, 'drop', '["#fff6e8", "#f7ddb2"]', '#9b5c14', '["30ml 단품", "30ml + 패드 증정", "2개 세트"]', '["빠른 흡수", "끈적임이 적은 라이트 세럼", "중건성·복합성 추천"]', '2026-07-10T00:00:00Z', now()),
  ('nova-buds', 'Nova Sparkle Earbuds', '테크', '크리스털 라이팅 포인트가 들어간 컴팩트 블루투스 이어버드', '컴팩트한 충전 케이스와 은은한 LED 포인트를 갖춘 무선 이어버드입니다.', 55900, 68000, 7, 'active', false, 'buds', '["#f2eeff", "#d7c8ff"]', '#6240c8', '["Lavender", "Silver Blue", "Pearl White"]', '["블루투스 무선 연결", "컴팩트 충전 케이스", "LED 라이팅 포인트"]', '2026-07-09T00:00:00Z', now()),
  ('satin-cap', 'Satin Stitch Ball Cap', '액세서리', '은은한 광택과 정돈된 스티치가 돋보이는 데일리 볼캡', '가볍게 눌러쓰는 실루엣과 톤온톤 스티치로 완성한 볼캡입니다.', 38800, 47000, 16, 'active', true, 'cap', '["#eef7f0", "#b9e7c7"]', '#1f7b47', '["Black", "Forest", "Cream"]', '["톤온톤 스티치", "사이즈 조절 스트랩", "은은한 새틴 광택"]', '2026-07-08T00:00:00Z', now()),
  ('jam-candle', 'Jam Pot Aroma Candle', '리빙', '잼 보틀을 닮은 작은 향초 오브제', '공간에 부드러운 향과 따뜻한 색을 더하는 유리 보틀 캔들입니다.', 33400, 41000, 20, 'active', false, 'jar', '["#fff3eb", "#ffd0b8"]', '#b14d1f', '["Butter Toast", "White Fig", "Milk Tea"]', '["유리 보틀 패키지", "선물용 종이 슬리브", "세 가지 시그니처 향"]', '2026-07-07T00:00:00Z', now())
on conflict (id) do nothing;

insert into public.posts (id, title, category, excerpt, content, status, pinned, created_at, updated_at) values
  ('post-summer-delivery', '여름 시즌 배송 일정 안내', 'notice', '주문량 증가에 따른 출고 일정과 고객센터 운영 시간을 안내합니다.', '평일 오후 2시 이전 결제 완료 주문은 당일 출고됩니다. 일부 주문 제작 상품은 상세 페이지의 출고 일정을 확인해 주세요.', 'published', true, '2026-07-14T02:00:00Z', '2026-07-14T02:00:00Z'),
  ('post-space-journal', '오래 머물고 싶은 공간을 만드는 법', 'journal', '좋아하는 물건을 천천히 고르고 배치하는 작은 방법을 소개합니다.', '공간의 인상은 물건의 수보다 여백과 반복되는 재료에서 시작합니다.', 'published', false, '2026-07-10T06:30:00Z', '2026-07-12T01:20:00Z'),
  ('post-member-week', '멤버 위크 사전 안내', 'event', '회원 전용 혜택과 선공개 상품을 준비하고 있습니다.', '이벤트 상세 혜택과 참여 방법은 오픈 당일 공개됩니다.', 'draft', false, '2026-07-15T04:00:00Z', '2026-07-15T04:00:00Z')
on conflict (id) do nothing;

insert into public.reviews (id, product_id, product_name, author, rating, option_name, body, status, created_at) values
  ('review-seed-1', 'orb-case', 'Orb Case', '김**', 5, 'Ivory', '사진보다 소재가 더 단정하고 수납도 생각보다 넉넉해요.', 'visible', '2026-07-12T05:20:00Z'),
  ('review-seed-2', 'cloud-bag', 'Cloud Bag', '이**', 4, 'Brown', '가볍고 매일 들기 좋아요. 포장도 깔끔했습니다.', 'visible', '2026-07-09T08:10:00Z'),
  ('review-seed-3', 'satin-cap', 'Satin Cap', '박**', 3, 'Black', '디자인은 마음에 들지만 포장이 조금 눌려서 도착했어요.', 'hidden', '2026-07-07T03:40:00Z')
on conflict (id) do nothing;
